# -*- coding: utf-8 -*-
"""D206 D1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3KyqWrWxe5Ylpjf3nQMZa1VVlgK55s7
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv ("churn_raw_data.csv")
df

df['InternetService'] = df['InternetService'].astype(str)

print("Missing values for each column:")
print(df.isnull())

print("\nCount of missing values in each column:")
print(df.isnull().sum())

print("\nAre there any missing values in the DataFrame?")
print(df.isnull().values.any())

print("\nTotal number of missing values:")
print(df.isnull().sum().sum())

duplicate_rows = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_rows}")

print("\nRows that are duplicates:")
print(df[df.duplicated()])

numeric_describe = df.describe()
print("\nDescriptive Statistics for Numeric Columns:\n", numeric_describe)

categorical_columns = df.select_dtypes(include=['object']).columns
unique_values = {col: df[col].nunique() for col in categorical_columns}
print("\nUnique Values in Categorical Columns:\n", unique_values)

numeric_columns = df.select_dtypes(include=['number']).columns
for col in numeric_columns:
    print(f"\nPotential anomalies in column '{col}':")
    print("Minimum Value:", df[col].min())
    print("Maximum Value:", df[col].max())