# -*- coding: utf-8 -*-
"""PCA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vqx9fQLn6xn62QM-LKc29o7y8z7ayT4l
"""

import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv ("D2.csv")
df

continuous_vars = ['Age', 'Income', 'Outage_sec_perweek',
                   'Tenure', 'MonthlyCharge', 'Bandwidth_GB_Year']

X = df[continuous_vars]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA()
pca_result = pca.fit(X_scaled)
print(pca_result)

explained_variance = pca.explained_variance_ratio_

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(explained_variance) + 1), np.cumsum(explained_variance), marker='o', linestyle='--')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Explained Variance by Principal Components')
plt.axhline(y=0.85, color='r', linestyle='--', label='85% Variance Threshold')
plt.legend()
plt.show()

loading_matrix = pd.DataFrame(
    pca.components_.T,
    columns=[f'PC{i+1}' for i in range(pca.n_components_)],
    index=continuous_vars
)

print("PCA Loading Matrix:")
print(loading_matrix)

print("\nExplained Variance Ratio:")
print(explained_variance)